kube:
  config:
    rootDirectory: '/opt/kube'
    clusters:
    - caFile: '/opt/kube/ca.crt'
      name: 'minikube'
      server: 'http://pubsub-emulator.default.svc.cluster.local:8443'
      skipTLSVerify: false
    contexts:
    - cluster: 'minikube'
      name: 'minikube'
      user: 'minikube'
    users:
    - certFile: '/opt/kube/client.crt'
      keyFile: '/opt/kube/client.key'
      name: 'minikube'
    currentContext: 'minikube'